name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      # Cache dependencies to speed up builds
      - uses: Swatinem/rust-cache@v2

      # Check formatting
      - name: Check formatting
        run: cargo fmt --all -- --check

      # Run clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # Run tests
      - name: Run tests
        run: cargo test --all-features

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      # Install cargo-tarpaulin for code coverage
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      # Generate code coverage report
      - name: Generate code coverage
        run: cargo tarpaulin --out Xml --all-features

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      # Build the project in release mode
      - name: Build project
        run: cargo build --release

  # Cross-platform testing
  cross-platform:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      # Run tests on different platforms
      - name: Run tests
        run: cargo test
